//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd_uchpr.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarColors
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CarColors()
        {
            this.Cars = new HashSet<Cars>();
        }
    
        public int id { get; set; }
        public string color_code { get; set; }
        public int color_name_type_id { get; set; }
        public Nullable<int> is_mettallic { get; set; }
    
        public virtual ColorNameTypes ColorNameTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cars> Cars { get; set; }
    }
}
