//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd_uchpr.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Fines = new HashSet<Fines>();
        }
    
        public int id { get; set; }
        public int driver_id { get; set; }
        public string VIN { get; set; }
        public int manufacturer_id { get; set; }
        public string model { get; set; }
        public string year { get; set; }
        public Nullable<int> weight { get; set; }
        public Nullable<int> color_id { get; set; }
        public int engine_type_id { get; set; }
        public int type_of__drive_id { get; set; }
        public Nullable<int> code_region_id { get; set; }
    
        public virtual CarColors CarColors { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual EngineTypes EngineTypes { get; set; }
        public virtual ManufacturerType ManufacturerType { get; set; }
        public virtual RegionCodes RegionCodes { get; set; }
        public virtual TypeOfDrive TypeOfDrive { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Fines> Fines { get; set; }
    }
}
