//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd_uchpr.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fines
    {
        public int id { get; set; }
        public int driver_id { get; set; }
        public int car_id { get; set; }
        public int state_id { get; set; }
        public int cost { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Drivers Drivers { get; set; }
        public virtual StateOfFines StateOfFines { get; set; }
    }
}
