//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd_uchpr.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Licenses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Licenses()
        {
            this.HistoryOfStatus = new HashSet<HistoryOfStatus>();
            this.Categories = new HashSet<Categories>();
        }
    
        public int id { get; set; }
        public string license_date { get; set; }
        public string expire_date { get; set; }
        public string license_series { get; set; }
        public string license_number { get; set; }
        public int driver_id { get; set; }
    
        public virtual Drivers Drivers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryOfStatus> HistoryOfStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Categories> Categories { get; set; }
    }
}
