//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gibdd_uchpr.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gibddEntities1 : DbContext
    {
        public gibddEntities1()
            : base("name=gibddEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarColors> CarColors { get; set; }
        public virtual DbSet<Cars> Cars { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<ColorNameTypes> ColorNameTypes { get; set; }
        public virtual DbSet<ColorTypes> ColorTypes { get; set; }
        public virtual DbSet<CompanyJob> CompanyJob { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<EngineTypes> EngineTypes { get; set; }
        public virtual DbSet<Fines> Fines { get; set; }
        public virtual DbSet<HistoryOfStatus> HistoryOfStatus { get; set; }
        public virtual DbSet<Licenses> Licenses { get; set; }
        public virtual DbSet<ManufacturerType> ManufacturerType { get; set; }
        public virtual DbSet<RegionCodes> RegionCodes { get; set; }
        public virtual DbSet<StateOfFines> StateOfFines { get; set; }
        public virtual DbSet<StateOfLicenses> StateOfLicenses { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeOfDrive> TypeOfDrive { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
